config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'children#index'

  resources :children do
    resources :records, only: [:new, :create, :index, :edit, :update, :destroy]
    resources :vaccination_records, only: [:index, :destroy] do
      collection do
        post :create_or_update
      end
    end
    resources :height_weights do
      collection do
        get :chart
      end
    end
  end

  resources :posts
  post 'select_child', to: 'children#select_child', as: :select_child

  resources :tags, only: [:index]

  resources :records, only: [:index] do
    collection do
      get :search
    end
  end

  resources :shared_users, only: [:index, :create, :destroy]
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :redirect_to_child_registration_if_none, only: [:new, :create]
  before_action :set_child, only: [:edit, :update, :destroy, :vaccination_schedule]
  before_action :ensure_owner_user, only: [:edit, :update, :destroy]

  def index
    @children = all_children
  end

  def new
    @child = Child.new
  end

  def create
    @child = current_user.children.new(child_params)
    if @child.save
      session[:child_id] = @child.id
      redirect_to children_path, notice: '登録しました！'
    else
      Rails.logger.debug "== errors: #{@child.errors.full_messages} =="
      render :new
    end
  end

  def edit
  end

  def update
    if @child.update(child_params)
      redirect_to children_path, notice: '更新しました！'
    else
      render :edit
    end
  end

  def destroy
    if @child.destroy
      redirect_to children_path, notice: '削除しました！'
    else
      redirect_to children_path, notice: '削除に失敗しました！'
    end
  end

  def select_child
    child = all_children.find { |c| c.id == params[:child_id].to_i }
    session[:child_id] = child.id
    redirect_to root_path, notice: "#{child.name} を選択しました"
  end

  def vaccination_schedule
    @vaccines = Vaccine.all
    @vaccination_schedules = @vaccines.map do |vaccine|
      next if vaccine.dose_month.blank?

      schedule_dates = vaccine.dose_months.map do |month|
        @child.birthday.advance(months: month)
      end

      {
        vaccine: vaccine,
        schedule_dates: schedule_dates
      }
    end.compact
  end

  private

  def set_child
    @child = all_children.find { |c| c.id == params[:id].to_i }
  end

  def child_params
    params.require(:child).permit(:name, :birthday, :gender, :allergy_info, :blood_type)
  end

  def ensure_owner_user
    return if owner_user?

    redirect_to root_path, alert: 'この操作はできません（閲覧専用です）'
  end
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/children/_form.html.erb
<div class="child-form-container">
  <%= form_with model: @child, local: true, class: 'child-form', data: { turbo: false } do |f| %>
    <%= render 'shared/error_messages', model: @child %>

    <div class="form-group">
      <%= f.label :name, '名前' %>
      <%= f.text_field :name, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= f.label :birthday, '誕生日' %>
      <%= f.date_field :birthday, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= f.label :gender, '性別' %>
      <%= f.select :gender,
        Child.genders.keys.map { |g| [t("activerecord.attributes.child.genders.#{g}"), g] },
        { include_blank: '選択してください' }, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= f.label :allergy_info, 'アレルギー' %>
      <%= f.text_field :allergy_info, class: 'form-input' %>
    </div>

    <div class="form-group">
      <%= f.label :blood_type, '血液型' %>
      <%= f.select :blood_type,
      Child.blood_types.keys.map { |b| [t("activerecord.attributes.child.blood_types.#{b}"), b] },
      { include_blank: '選択してください' }, class: 'form-input' %>
    </div>

    <div class="form-actions">
      <%= f.submit '登録', class: 'btn btn-primary btn-full' %>
    </div>

  <% end %>
</div>

app/views/children/edit.html.erb
<h1>こどもの編集</h1>
<%= render 'form' %>

app/views/children/index.html.erb
<div class="body__container">
  <div class="children-header">
    <div class="children-header-content">
      <h1>こども一覧</h1>
      <% if owner_user? %>
        <%= link_to new_child_path, class: 'btn-add-child' do %>
          <%= image_tag 'add.png', alt: '追加', class: "icon-image" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="children-container">
    <div class="children-list">
      <% @children.each do |child| %>
      <div class="child-form">
        <p><strong>名前:</strong> <%= child.name %>（<%= child.age_in_years_and_months %>）</p>
          <p><strong>生年月日:</strong> <%= child.birthday %></p>
          <p><strong>性別:</strong> <%= I18n.t("activerecord.attributes.child.genders.#{child.gender}") %></p>
          <p><strong>アレルギー情報:</strong> <%= child.allergy_info.presence || 'なし' %></p>
          <p><strong>血液型:</strong> <%= I18n.t("activerecord.attributes.child.blood_types.#{child.blood_type}") %></p>
          <div class="form-actions">
            <% if owner_user? %>
              <%= link_to '編集', edit_child_path(child), class: 'btn btn-secondary btn-full' %>
              <%= link_to '削除', child_path(child), data: { turbo_method: :delete, confirm: '本当に削除しますか？' }, class: 'btn btn-danger btn-full' %>
            <% end %>

            <% if child == current_child %>
              <button class="btn btn-selected btn-full" disabled>選択中</button>
            <% else %>
              <%= button_to '選択する', select_child_path(child_id: child.id), method: :post, class: 'btn btn-primary btn-full', form: { class: 'btn-form' } %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/children/new.html.erb
<h1>こどもの登録</h1>
<%= render 'form' %>