config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'children#index'

  resources :children do
    resources :records, only: [:new, :create, :index, :edit, :update, :destroy]
    resources :vaccination_records, only: [:index, :destroy] do
      collection do
        post :create_or_update
      end
    end
    resources :height_weights do
      collection do
        get :chart
      end
    end
  end

  resources :posts
  post 'select_child', to: 'children#select_child', as: :select_child

  resources :tags, only: [:index]

  resources :records, only: [:index] do
    collection do
      get :search
    end
  end

  resources :shared_users, only: [:index, :create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<% show_fab =
     (controller_name == 'children' && action_name == 'index') ||
     (controller_name == 'records' && action_name == 'index') %>
<% if owner_user? && controller_name != 'shared_users' && show_fab %>
  <button class="fab">
    <%= link_to new_child_record_path(current_child), class: "fab-link" do %>
      <img src="<%= asset_path('pen.png') %>" alt="投稿" class="icon-image">
    <% end %>
  </button>
<% end %>

<% if current_child.present? || shared_user? %>
  <nav class="bottom-tabs">
    <div class="tab-container">
      <div class="tab-item">
        <%= link_to root_path, class: "tab-link" do %>
          <div class="tab-icon">
            <img src="<%= asset_path('home.png') %>" alt="ホーム" class="icon-image">
          </div>
          <div class="tab-label">ホーム</div>
        <% end %>
      </div>
      <div class="tab-item">
        <%= link_to child_records_path(current_child), class: "tab-link" do %>
          <div class="tab-icon">
            <img src="<%= asset_path('kiroku.png') %>" alt="記録" class="icon-image">
          </div>
          <div class="tab-label">記録</div>
        <% end %>
      </div>
      <div class="tab-item">
        <%= link_to child_height_weights_path(current_child), class: "tab-link" do %>
          <div class="tab-icon">
            <img src="<%= asset_path('graph.png') %>" alt="成長" class="icon-image">
          </div>
          <div class="tab-label">成長</div>
        <% end %>
      </div>
      <div class="tab-item">
        <%= link_to child_vaccination_records_path(current_child), class: "tab-link" do %>
          <div class="tab-icon">
            <img src="<%= asset_path('vaccine.png') %>" alt="予防接種" class="icon-image">
          </div>
          <div class="tab-label">予防接種</div>
        <% end %>
      </div>
      <div class="tab-item">
        <%= link_to shared_users_path, class: "tab-link" do %>
          <div class="tab-icon">
            <img src="<%= asset_path('setting.png') %>" alt="家族" class="icon-image">
          </div>
          <div class="tab-label">設定</div>
        <% end %>
      </div>
    </div>
  </nav>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header-content">
    <%= link_to root_path, class: "logo" do %>
      <%= image_tag "logo.png", alt: "Kids Journal Logo", class: "logo-image" %>
    <% end %>

    <% if user_signed_in? %>
      <div class="header-actions">
        <%= link_to 'ログアウト', destroy_user_session_path, 
              class: "logout-btn", 
              data: { turbo_method: :delete } %>
        <%= link_to search_records_path, class: "icon-btn" do %>
          <%= image_tag "find.png", alt: "検索", class: "icon-image" %>
        <% end %>
      </div>
    <% end %>
  </div>
</header>